module.exports =
  'symbols:dot': ['format:camel']
  'cursor:down': ['cursor:way-left', 'cursor:way-right', 'cursor:down']
  'cursor:up': ['cursor:way-left', 'cursor:way-right', 'cursor:up']
  'selection:block': ['mouse:shift-click']
  'selection:all': ['common:delete']
  'common:delete': ['common:enter']
  'common:forward-delete': ['common:enter']
  'symbols:slash': ['repetition:command-2']
  'symbols:hashtag': ['repetition:command-2']
  'atom:select-scope': ['repetition:command-2']
  'delete:word': ['common:enter']
  'delete:word-forward': ['common:enter']
